### ISSUE TITLE
Expose a did generation endpoint

### ISSUE THREAD

**Issue by patatoid** [decentralized-identity/uni-resolver-driver-did-key#12]
Hi,

I am looking forward to generate ebsi compliant did keys for the compliance test suite. I am not sure about the interface to expose. Is there any requirements about this?

**Comment by peacekeeper** [comment]
Hello, this repo here contains a resolver driver for did:key. There is also a registrar driver for did:key that can create DIDs: https://github.com/decentralized-identity/uni-registrar-driver-did-key

But I'm not sure right now if it supports EBSI-style did:key to be honest.

**Comment by patatoid** [comment]
Hi,

Thank you for your reply. I was not aware about the registrar repository, thanks for pointing it out.

I think it is possible to integrate the cef-ebsi package into the registrar to craft ebsi dids. I will submit a pull request if you please.

Is there any way to expose the registrar?
